<?php
//require_once('plugins/wp-less/wp-less.php');
include_once('functions/custom-functions.php');
include_once('functions/registers.php');
include_once('functions/posttypes.php');
include_once('functions/sidebars.php');
include_once('functions/nav-walkers.php');
include_once('functions/thumbnails.php');
include_once('functions/shortcodes.php');
include_once('functions/widgets.php');
?>